"""
Exercise Database for Jonny Valdez Coaching System
Domain Athletics — Folsom, CA

Every exercise is tagged with metadata that maps to the coaching framework:
  - Resistance profiles matched to strength curves
  - Fatigue cost for intelligent programming
  - Complexity appropriate for general population clients
  - Hypertrophy pillar alignment (mechanical tension / metabolic stress / muscle damage)
"""

EXERCISES = [
    # =========================================================================
    # GLUTES
    # =========================================================================
    {
        "name": "KAS glute bridge",
        "muscle_group": "glutes",
        "secondary_muscles": ["hamstrings"],
        "resistance_profile": "free_weight",
        "strength_curve_bias": "shortened",
        "fatigue_cost": "low",
        "complexity": "beginner",
        "equipment": "barbell",
        "hypertrophy_pillar": "metabolic_stress",
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest": "90 sec",
        "coaching_cue": "Squeeze at the top for a 2-count. Drive through heels, lock out the hips fully.",
    },
    {
        "name": "hip thrust",
        "muscle_group": "glutes",
        "secondary_muscles": ["hamstrings", "quads"],
        "resistance_profile": "free_weight",
        "strength_curve_bias": "shortened",
        "fatigue_cost": "moderate",
        "complexity": "intermediate",
        "equipment": "barbell",
        "hypertrophy_pillar": "mechanical_tension",
        "default_sets": 3,
        "default_reps": "8-10",
        "default_rest": "2 min",
        "coaching_cue": "Chin tucked, ribs down. Drive hips to full lockout, pause at the top.",
    },
    {
        "name": "glute medius kickback",
        "muscle_group": "glutes",
        "secondary_muscles": [],
        "resistance_profile": "cable",
        "strength_curve_bias": "shortened",
        "fatigue_cost": "low",
        "complexity": "beginner",
        "equipment": "cable",
        "hypertrophy_pillar": "metabolic_stress",
        "default_sets": 3,
        "default_reps": "15-20",
        "default_rest": "60 sec",
        "coaching_cue": "Slight hip abduction on the kick. Keep pelvis neutral, squeeze the outside of the hip.",
    },
    {
        "name": "cable kickback",
        "muscle_group": "glutes",
        "secondary_muscles": ["hamstrings"],
        "resistance_profile": "cable",
        "strength_curve_bias": "shortened",
        "fatigue_cost": "low",
        "complexity": "beginner",
        "equipment": "cable",
        "hypertrophy_pillar": "metabolic_stress",
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest": "60 sec",
        "coaching_cue": "Hinge slightly at the hip, extend straight back. Squeeze at end range, don't hyperextend the low back.",
    },
    {
        "name": "cable pull-through",
        "muscle_group": "glutes",
        "secondary_muscles": ["hamstrings"],
        "resistance_profile": "cable",
        "strength_curve_bias": "lengthened",
        "fatigue_cost": "low",
        "complexity": "beginner",
        "equipment": "cable",
        "hypertrophy_pillar": "muscle_damage",
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest": "90 sec",
        "coaching_cue": "Push hips back until you feel the stretch in the hamstrings, then snap the hips forward to lockout.",
    },

    # =========================================================================
    # QUADS
    # =========================================================================
    {
        "name": "goblet squat",
        "muscle_group": "quads",
        "secondary_muscles": ["glutes", "core"],
        "resistance_profile": "free_weight",
        "strength_curve_bias": "lengthened",
        "fatigue_cost": "moderate",
        "complexity": "beginner",
        "equipment": "dumbbell",
        "hypertrophy_pillar": "muscle_damage",
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest": "2 min",
        "coaching_cue": "Sit between the hips, elbows inside the knees. Control the descent, own the bottom position.",
    },
    {
        "name": "hack squat",
        "muscle_group": "quads",
        "secondary_muscles": ["glutes"],
        "resistance_profile": "machine",
        "strength_curve_bias": "lengthened",
        "fatigue_cost": "high",
        "complexity": "intermediate",
        "equipment": "machine",
        "hypertrophy_pillar": "mechanical_tension",
        "default_sets": 3,
        "default_reps": "8-10",
        "default_rest": "3 min",
        "coaching_cue": "Feet shoulder-width, low on the platform. Descend deep, push through the full foot.",
    },
    {
        "name": "leg press",
        "muscle_group": "quads",
        "secondary_muscles": ["glutes"],
        "resistance_profile": "machine",
        "strength_curve_bias": "lengthened",
        "fatigue_cost": "moderate",
        "complexity": "beginner",
        "equipment": "machine",
        "hypertrophy_pillar": "mechanical_tension",
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest": "2 min",
        "coaching_cue": "Lower until the knees pass 90 degrees. Keep the low back pinned to the pad. Press evenly through both feet.",
    },
    {
        "name": "leg extension",
        "muscle_group": "quads",
        "secondary_muscles": [],
        "resistance_profile": "machine",
        "strength_curve_bias": "shortened",
        "fatigue_cost": "low",
        "complexity": "beginner",
        "equipment": "machine",
        "hypertrophy_pillar": "metabolic_stress",
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest": "90 sec",
        "coaching_cue": "Squeeze the quads hard at the top. Slow eccentric, 2-3 seconds on the way down.",
    },
    {
        "name": "Bulgarian split squat",
        "muscle_group": "quads",
        "secondary_muscles": ["glutes", "core"],
        "resistance_profile": "free_weight",
        "strength_curve_bias": "lengthened",
        "fatigue_cost": "high",
        "complexity": "intermediate",
        "equipment": "dumbbell",
        "hypertrophy_pillar": "muscle_damage",
        "default_sets": 3,
        "default_reps": "8-10",
        "default_rest": "2 min",
        "coaching_cue": "Slight forward lean, front shin vertical. Drop the back knee straight down, stay balanced.",
    },
    {
        "name": "walking lunge",
        "muscle_group": "quads",
        "secondary_muscles": ["glutes", "hamstrings", "core"],
        "resistance_profile": "free_weight",
        "strength_curve_bias": "lengthened",
        "fatigue_cost": "high",
        "complexity": "intermediate",
        "equipment": "dumbbell",
        "hypertrophy_pillar": "muscle_damage",
        "default_sets": 3,
        "default_reps": "10-12 each",
        "default_rest": "2 min",
        "coaching_cue": "Long stride, control the landing. Drive through the front heel to stand. Keep the torso upright.",
    },
    {
        "name": "reverse lunge",
        "muscle_group": "quads",
        "secondary_muscles": ["glutes", "core"],
        "resistance_profile": "free_weight",
        "strength_curve_bias": "lengthened",
        "fatigue_cost": "moderate",
        "complexity": "beginner",
        "equipment": "dumbbell",
        "hypertrophy_pillar": "muscle_damage",
        "default_sets": 3,
        "default_reps": "10-12 each",
        "default_rest": "90 sec",
        "coaching_cue": "Step back, drop the knee to hover above the floor. Push through the front foot to return.",
    },

    # =========================================================================
    # HAMSTRINGS
    # =========================================================================
    {
        "name": "RDL",
        "muscle_group": "hamstrings",
        "secondary_muscles": ["glutes", "lower back"],
        "resistance_profile": "free_weight",
        "strength_curve_bias": "lengthened",
        "fatigue_cost": "high",
        "complexity": "intermediate",
        "equipment": "barbell",
        "hypertrophy_pillar": "muscle_damage",
        "default_sets": 3,
        "default_reps": "8-10",
        "default_rest": "3 min",
        "coaching_cue": "Push the hips back, keep the bar glued to your legs. Feel the stretch in the hamstrings before driving hips forward.",
    },
    {
        "name": "lying leg curl",
        "muscle_group": "hamstrings",
        "secondary_muscles": [],
        "resistance_profile": "machine",
        "strength_curve_bias": "mid_range",
        "fatigue_cost": "low",
        "complexity": "beginner",
        "equipment": "machine",
        "hypertrophy_pillar": "mechanical_tension",
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest": "90 sec",
        "coaching_cue": "Keep hips pressed into the pad. Curl with control, squeeze at the top, slow on the way down.",
    },
    {
        "name": "seated leg curl",
        "muscle_group": "hamstrings",
        "secondary_muscles": [],
        "resistance_profile": "machine",
        "strength_curve_bias": "lengthened",
        "fatigue_cost": "low",
        "complexity": "beginner",
        "equipment": "machine",
        "hypertrophy_pillar": "muscle_damage",
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest": "90 sec",
        "coaching_cue": "Start from a fully stretched position. Curl through the full range, control the eccentric.",
    },
    {
        "name": "single-leg RDL",
        "muscle_group": "hamstrings",
        "secondary_muscles": ["glutes", "core"],
        "resistance_profile": "free_weight",
        "strength_curve_bias": "lengthened",
        "fatigue_cost": "moderate",
        "complexity": "advanced",
        "equipment": "dumbbell",
        "hypertrophy_pillar": "muscle_damage",
        "default_sets": 3,
        "default_reps": "8-10 each",
        "default_rest": "90 sec",
        "coaching_cue": "Hinge at the hip, reach the weight toward the floor. Back leg extends behind you. Stay square.",
    },

    # =========================================================================
    # CHEST
    # =========================================================================
    {
        "name": "incline DB press",
        "muscle_group": "chest",
        "secondary_muscles": ["shoulders", "triceps"],
        "resistance_profile": "free_weight",
        "strength_curve_bias": "lengthened",
        "fatigue_cost": "moderate",
        "complexity": "intermediate",
        "equipment": "dumbbell",
        "hypertrophy_pillar": "muscle_damage",
        "default_sets": 3,
        "default_reps": "8-10",
        "default_rest": "2 min",
        "coaching_cue": "30-degree incline. Lower with control, feel the stretch at the bottom, press to full lockout.",
    },
    {
        "name": "chest press machine",
        "muscle_group": "chest",
        "secondary_muscles": ["shoulders", "triceps"],
        "resistance_profile": "machine",
        "strength_curve_bias": "mid_range",
        "fatigue_cost": "low",
        "complexity": "beginner",
        "equipment": "machine",
        "hypertrophy_pillar": "mechanical_tension",
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest": "2 min",
        "coaching_cue": "Set the seat so handles align with mid-chest. Press to lockout, control the return.",
    },
    {
        "name": "cable fly",
        "muscle_group": "chest",
        "secondary_muscles": ["shoulders"],
        "resistance_profile": "cable",
        "strength_curve_bias": "shortened",
        "fatigue_cost": "low",
        "complexity": "beginner",
        "equipment": "cable",
        "hypertrophy_pillar": "metabolic_stress",
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest": "90 sec",
        "coaching_cue": "Slight bend in the elbows, bring hands together in front of the chest. Squeeze hard at the peak.",
    },
    {
        "name": "push-up",
        "muscle_group": "chest",
        "secondary_muscles": ["shoulders", "triceps", "core"],
        "resistance_profile": "bodyweight",
        "strength_curve_bias": "mid_range",
        "fatigue_cost": "low",
        "complexity": "beginner",
        "equipment": "bodyweight",
        "hypertrophy_pillar": "mechanical_tension",
        "default_sets": 3,
        "default_reps": "10-15",
        "default_rest": "90 sec",
        "coaching_cue": "Hands under shoulders, body rigid like a plank. Lower chest to the floor, press back up. No sagging hips.",
    },

    # =========================================================================
    # BACK
    # =========================================================================
    {
        "name": "T-bar row",
        "muscle_group": "back",
        "secondary_muscles": ["biceps", "rear delts"],
        "resistance_profile": "free_weight",
        "strength_curve_bias": "mid_range",
        "fatigue_cost": "high",
        "complexity": "intermediate",
        "equipment": "barbell",
        "hypertrophy_pillar": "mechanical_tension",
        "default_sets": 3,
        "default_reps": "8-10",
        "default_rest": "2 min",
        "coaching_cue": "Chest supported or hinged at 45 degrees. Pull to the sternum, squeeze the shoulder blades.",
    },
    {
        "name": "seated cable row",
        "muscle_group": "back",
        "secondary_muscles": ["biceps", "rear delts"],
        "resistance_profile": "cable",
        "strength_curve_bias": "mid_range",
        "fatigue_cost": "moderate",
        "complexity": "beginner",
        "equipment": "cable",
        "hypertrophy_pillar": "mechanical_tension",
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest": "2 min",
        "coaching_cue": "Sit tall, pull the handle to the belly button. Retract the shoulder blades, control the return.",
    },
    {
        "name": "lat pulldown",
        "muscle_group": "back",
        "secondary_muscles": ["biceps"],
        "resistance_profile": "cable",
        "strength_curve_bias": "lengthened",
        "fatigue_cost": "moderate",
        "complexity": "beginner",
        "equipment": "cable",
        "hypertrophy_pillar": "muscle_damage",
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest": "2 min",
        "coaching_cue": "Lean slightly back, pull the bar to the upper chest. Let the lats stretch fully at the top.",
    },
    {
        "name": "chest-supported row",
        "muscle_group": "back",
        "secondary_muscles": ["biceps", "rear delts"],
        "resistance_profile": "free_weight",
        "strength_curve_bias": "mid_range",
        "fatigue_cost": "moderate",
        "complexity": "beginner",
        "equipment": "dumbbell",
        "hypertrophy_pillar": "mechanical_tension",
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest": "2 min",
        "coaching_cue": "Chest on the pad, let the arms hang. Row to the hip, squeeze the shoulder blades, lower with control.",
    },
    {
        "name": "DB row",
        "muscle_group": "back",
        "secondary_muscles": ["biceps", "rear delts", "core"],
        "resistance_profile": "free_weight",
        "strength_curve_bias": "mid_range",
        "fatigue_cost": "moderate",
        "complexity": "beginner",
        "equipment": "dumbbell",
        "hypertrophy_pillar": "mechanical_tension",
        "default_sets": 3,
        "default_reps": "8-10",
        "default_rest": "90 sec",
        "coaching_cue": "One hand on the bench, flat back. Row to the hip, elbow past the torso. Don't rotate.",
    },

    # =========================================================================
    # SHOULDERS
    # =========================================================================
    {
        "name": "seated shoulder press",
        "muscle_group": "shoulders",
        "secondary_muscles": ["triceps", "core"],
        "resistance_profile": "free_weight",
        "strength_curve_bias": "mid_range",
        "fatigue_cost": "moderate",
        "complexity": "intermediate",
        "equipment": "dumbbell",
        "hypertrophy_pillar": "mechanical_tension",
        "default_sets": 3,
        "default_reps": "8-10",
        "default_rest": "2 min",
        "coaching_cue": "Press from ear level to full lockout overhead. Keep the core tight, don't flare the ribs.",
    },
    {
        "name": "seated lateral raise",
        "muscle_group": "shoulders",
        "secondary_muscles": [],
        "resistance_profile": "free_weight",
        "strength_curve_bias": "lengthened",
        "fatigue_cost": "low",
        "complexity": "beginner",
        "equipment": "dumbbell",
        "hypertrophy_pillar": "muscle_damage",
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest": "60 sec",
        "coaching_cue": "Slight lean forward, raise to shoulder height. Lead with the elbow, control the descent.",
    },
    {
        "name": "DB rear delt fly",
        "muscle_group": "shoulders",
        "secondary_muscles": ["upper back"],
        "resistance_profile": "free_weight",
        "strength_curve_bias": "lengthened",
        "fatigue_cost": "low",
        "complexity": "beginner",
        "equipment": "dumbbell",
        "hypertrophy_pillar": "muscle_damage",
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest": "60 sec",
        "coaching_cue": "Hinged at the hips, arms slightly bent. Raise out to the sides, squeeze the rear delts.",
    },
    {
        "name": "cable lateral raise",
        "muscle_group": "shoulders",
        "secondary_muscles": [],
        "resistance_profile": "cable",
        "strength_curve_bias": "mid_range",
        "fatigue_cost": "low",
        "complexity": "beginner",
        "equipment": "cable",
        "hypertrophy_pillar": "metabolic_stress",
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest": "60 sec",
        "coaching_cue": "Cable at hip height, cross-body pull. Raise to shoulder height with constant tension.",
    },
    {
        "name": "face pull",
        "muscle_group": "shoulders",
        "secondary_muscles": ["upper back", "rear delts"],
        "resistance_profile": "cable",
        "strength_curve_bias": "shortened",
        "fatigue_cost": "low",
        "complexity": "beginner",
        "equipment": "cable",
        "hypertrophy_pillar": "metabolic_stress",
        "default_sets": 3,
        "default_reps": "15-20",
        "default_rest": "60 sec",
        "coaching_cue": "Pull the rope to your face, separate the ends. Externally rotate at end range, squeeze the upper back.",
    },

    # =========================================================================
    # ARMS
    # =========================================================================
    {
        "name": "cable curl",
        "muscle_group": "arms",
        "secondary_muscles": ["forearms"],
        "resistance_profile": "cable",
        "strength_curve_bias": "mid_range",
        "fatigue_cost": "low",
        "complexity": "beginner",
        "equipment": "cable",
        "hypertrophy_pillar": "mechanical_tension",
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest": "60 sec",
        "coaching_cue": "Elbows pinned to your sides. Curl with control, squeeze at the top, slow eccentric.",
    },
    {
        "name": "triceps pressdown",
        "muscle_group": "arms",
        "secondary_muscles": [],
        "resistance_profile": "cable",
        "strength_curve_bias": "shortened",
        "fatigue_cost": "low",
        "complexity": "beginner",
        "equipment": "cable",
        "hypertrophy_pillar": "metabolic_stress",
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest": "60 sec",
        "coaching_cue": "Elbows tight to the body. Press to full lockout, squeeze the triceps, control the return.",
    },
    {
        "name": "hammer curl",
        "muscle_group": "arms",
        "secondary_muscles": ["forearms", "brachialis"],
        "resistance_profile": "free_weight",
        "strength_curve_bias": "mid_range",
        "fatigue_cost": "low",
        "complexity": "beginner",
        "equipment": "dumbbell",
        "hypertrophy_pillar": "mechanical_tension",
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest": "60 sec",
        "coaching_cue": "Neutral grip, thumbs up. Curl without swinging, control the negative.",
    },
    {
        "name": "overhead triceps extension",
        "muscle_group": "arms",
        "secondary_muscles": [],
        "resistance_profile": "cable",
        "strength_curve_bias": "lengthened",
        "fatigue_cost": "low",
        "complexity": "beginner",
        "equipment": "cable",
        "hypertrophy_pillar": "muscle_damage",
        "default_sets": 3,
        "default_reps": "10-12",
        "default_rest": "60 sec",
        "coaching_cue": "Face away from the cable, arms overhead. Extend fully, feel the stretch in the long head on the way down.",
    },

    # =========================================================================
    # CALVES
    # =========================================================================
    {
        "name": "standing calf raise",
        "muscle_group": "calves",
        "secondary_muscles": [],
        "resistance_profile": "machine",
        "strength_curve_bias": "shortened",
        "fatigue_cost": "low",
        "complexity": "beginner",
        "equipment": "machine",
        "hypertrophy_pillar": "metabolic_stress",
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest": "60 sec",
        "coaching_cue": "Full range of motion. Stretch at the bottom, pause at the top. Straight knees to target the gastroc.",
    },
    {
        "name": "seated calf raise",
        "muscle_group": "calves",
        "secondary_muscles": [],
        "resistance_profile": "machine",
        "strength_curve_bias": "shortened",
        "fatigue_cost": "low",
        "complexity": "beginner",
        "equipment": "machine",
        "hypertrophy_pillar": "metabolic_stress",
        "default_sets": 3,
        "default_reps": "15-20",
        "default_rest": "60 sec",
        "coaching_cue": "Bent knees to target the soleus. Full stretch at the bottom, hard squeeze at the top.",
    },

    # =========================================================================
    # CORE
    # =========================================================================
    {
        "name": "plank",
        "muscle_group": "core",
        "secondary_muscles": ["shoulders"],
        "resistance_profile": "bodyweight",
        "strength_curve_bias": "mid_range",
        "fatigue_cost": "low",
        "complexity": "beginner",
        "equipment": "bodyweight",
        "hypertrophy_pillar": "mechanical_tension",
        "default_sets": 3,
        "default_reps": "30-45 sec",
        "default_rest": "60 sec",
        "coaching_cue": "Elbows under shoulders, body rigid. Squeeze glutes, brace abs, breathe. No sagging or piking.",
    },
    {
        "name": "pallof press",
        "muscle_group": "core",
        "secondary_muscles": ["obliques"],
        "resistance_profile": "cable",
        "strength_curve_bias": "mid_range",
        "fatigue_cost": "low",
        "complexity": "beginner",
        "equipment": "cable",
        "hypertrophy_pillar": "mechanical_tension",
        "default_sets": 3,
        "default_reps": "10-12 each",
        "default_rest": "60 sec",
        "coaching_cue": "Stand perpendicular to the cable. Press hands straight out, resist rotation. Hold 2 seconds at full extension.",
    },
    {
        "name": "dead bug",
        "muscle_group": "core",
        "secondary_muscles": [],
        "resistance_profile": "bodyweight",
        "strength_curve_bias": "mid_range",
        "fatigue_cost": "low",
        "complexity": "beginner",
        "equipment": "bodyweight",
        "hypertrophy_pillar": "mechanical_tension",
        "default_sets": 3,
        "default_reps": "8-10 each",
        "default_rest": "60 sec",
        "coaching_cue": "Low back flat to the floor. Extend opposite arm and leg, exhale as you extend. No arching.",
    },
    {
        "name": "cable crunch",
        "muscle_group": "core",
        "secondary_muscles": [],
        "resistance_profile": "cable",
        "strength_curve_bias": "shortened",
        "fatigue_cost": "low",
        "complexity": "beginner",
        "equipment": "cable",
        "hypertrophy_pillar": "metabolic_stress",
        "default_sets": 3,
        "default_reps": "12-15",
        "default_rest": "60 sec",
        "coaching_cue": "Kneeling under the cable, rope behind the head. Crunch ribs toward hips, squeeze the abs hard.",
    },
]


def get_exercises_for_muscle_group(group: str) -> list[dict]:
    """Return all exercises that target the given primary muscle group.

    Args:
        group: Primary muscle group name (e.g. "glutes", "quads", "chest").

    Returns:
        List of exercise dicts whose muscle_group matches.
    """
    return [ex for ex in EXERCISES if ex["muscle_group"] == group.lower()]


def filter_exercises(**kwargs) -> list[dict]:
    """Filter exercises by any combination of metadata fields.

    Supports special handling for:
      - complexity: "beginner" also matches exercises tagged "all"
      - All other fields: exact match

    Args:
        **kwargs: Field-value pairs to filter on (e.g. equipment="cable",
                  complexity="beginner", muscle_group="back").

    Returns:
        List of exercise dicts matching ALL provided filters.
    """
    results = EXERCISES
    for key, value in kwargs.items():
        if key == "complexity":
            results = [
                ex for ex in results
                if ex.get("complexity") == value or ex.get("complexity") == "all"
            ]
        else:
            results = [ex for ex in results if ex.get(key) == value]
    return results
